report:
  excel_path: ./report/excel/
  check_log: ./report/logs/check_log/check.log
  serial_log: ./report/logs/run_log/auto_run.log
  test_log: ./report/logs/test_logs/test_result.log
  sub_labels_log: ./report/logs/run_log/sub_labels.log

yolo_model: ./runner/model/{}.pt
labelImg_classes_path: ./labelImg/data/predefined_classes.txt

game_serial_number:
  - LOL                 # 0
  - Apex_Legends        # 1
  - Valorant            # 2
  - Overwatch           # 3
  - Fortnite            # 4
  - csgo                # 5
  - pubg                # 6
  - cod                 # 7

classes_txt_path: ./runner/classes/{}.txt

images:
  bg: ./runner/images/background/bg.png
  icon: ./runner/images/icon/

Lamp_effect:
  "0":
    - 110
    - 301
    - 104
    - 110
    - 401
    - 104
    - 104
    - 104
    - 104
    - 104
    - 202
    - 302
    - 108
    - 102
    - 102
    - 106
    - 108
    - 401
    - 106
    - 109
    - 110
    - 105
    - 105
    - 105
    - 105
    - 105
    - 402
    - 107
    - 109
    - 111
    - 109
    - 110
    - 110
    - 202
    - 202

  "1":
    - 104
    - 301
    - 102
    - 301
    - 109
    - 106
    - 102
    - 112
    - 501
    - 112
    - 501
    - 112
    - 112
    - 112
    - 109
    - 109
    - 110
    - 202
    - 105
    - 105
    - 106
    - 105
    - 302
    - 108
    - 109

  "2":
    - 104
    - 109
    - 302
    - 301
    - 301
    - 109
    - 203
    - 104
    - 109
    - 203
    - 102
    - 302
    - 402
    - 401
    - 401
    - 106

  "3":
    - 401
    - 104
    - 104
    - 108
    - 110
    - 102
    - 105
    - 301
    - 108
    - 401


