path: D:\Kahoku\HDMI-DATA\Game_Pictures\Fortnite\pictures\Fortnite
train: # train images (relative to 'path')  16551 images
  - train/images
val: # val images (relative to 'path')  4952 images
  - val/images

# Classes
names:
  0: Matching
  1: Matched
  2: Skydive
  3: Gliding
  4: Build1
  5: Build2
  6: Eliminated
  7: Eliminated_BY_X
  8: Level_Up
  9: Search
  10: Victory